# -*- coding: utf-8 -*-
"""model_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elHYM0vfaoewaQA702vHrvEbtsHzg9GJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import torch
import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

import matplotlib.pyplot as plt
import numpy as np

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))


# get some random training images
dataiter = iter(trainloader)
images, labels = next(dataiter)

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))

import torch.nn as nn
import torch.nn.functional as F
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print(device)

class Net(nn.Module):
    def __init__(self, num_classes=10):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=5, padding=2)
        self.conv2 = nn.Conv2d(3, 64, kernel_size=5, padding=2)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=5, padding=2)
        self.conv4 = nn.Conv2d(128, 128, kernel_size=5, padding=2)

        self.pool1 = nn.MaxPool2d(2, 2)

        self.conv5 = nn.Conv2d(128, 224, kernel_size=5, padding=2)
        self.conv6 = nn.Conv2d(128, 224, kernel_size=5, padding=2)

        self.pool2 = nn.MaxPool2d(2, 2)

        self.conv7 = nn.Conv2d(224, 448, kernel_size=5, padding=2)

        self.conv8 = nn.Conv2d(224, 224, kernel_size=5, padding=2)

        self.conv9 = nn.Conv2d(448, 224, kernel_size=5, padding=2)
        self.conv10 = nn.Conv2d(224, 448, kernel_size=5, padding=2)

        self.pool3 = nn.MaxPool2d(2, 2)

        self.conv_dotted = nn.Conv2d(448, 256, kernel_size=5, padding=2)

        self.conv11 = nn.Conv2d(256, 256, kernel_size=5, padding=2)

        self.pool4 = nn.MaxPool2d(2, 2)

        self.conv_final = nn.Conv2d(256, 256, kernel_size=5, padding=2)

        self.fc = nn.Linear(256 * 4 * 4, num_classes)

        self.bn64 = nn.BatchNorm2d(64)
        self.bn128 = nn.BatchNorm2d(128)
        self.bn224 = nn.BatchNorm2d(224)
        self.bn448 = nn.BatchNorm2d(448)
        self.bn256 = nn.BatchNorm2d(256)
        self.bn128_final = nn.BatchNorm2d(128)

    def forward(self, x):
        x1 = F.relu(self.bn64(self.conv1(x)))
        x3 = F.relu(self.bn128(self.conv3(x1)))
        x3_pool = self.pool1(x3)

        x2 = F.relu(self.bn64(self.conv2(x)))

        x_cat1 = torch.cat([x1, x2], dim=1)
        x4 = F.relu(self.bn128(self.conv4(x_cat1)))
        x6 = F.relu(self.bn224(self.conv6(x4)))
        x6_pool = self.pool2(x6)

        x5 = F.relu(self.bn224(self.conv5(x3_pool)))
        x7 = F.relu(self.bn448(self.conv7(x5)))

        x_cat2 = torch.cat([x5, x6_pool], dim=1)
        x_add1 = x7 + x_cat2

        x8 = F.relu(self.bn224(self.conv8(x6_pool)))
        x9 = F.relu(self.bn224(self.conv9(x_add1)))
        x10 = F.relu(self.bn448(self.conv10(x9)))

        x_cat3 = torch.cat([x8, x9], dim=1)
        x_add2 = x_cat3 + x10

        out = self.pool3(x_add2)

        out = F.relu(self.bn256(self.conv_dotted(out)))

        out = F.relu(self.bn256(self.conv11(out)))
        out = self.pool4(out)

        out = F.relu(self.bn256(self.conv_final(out)))

        out = out.view(out.size(0), -1)
        out = self.fc(out)

        return out

net = Net()
from torchsummary import summary
net = net.to(device)
summary(net, (3, 32, 32))

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

for epoch in range(10):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs
        inputs, labels = data[0].to(device), data[1].to(device)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

dataiter = iter(testloader)
images, labels = next(dataiter)

# print images
imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))

images, labels = data[0].to(device), data[1].to(device)
outputs = net(images)

_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]
                              for j in range(4)))

correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data[0].to(device), data[1].to(device)

        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy of the network on the 10000 test images: %d %%' % (
    100 * correct / total))

class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))

with torch.no_grad():
    for data in testloader:
        images, labels = data[0].to(device), data[1].to(device)

        outputs = net(images)
        _, predicted = torch.max(outputs, 1)
        c = (predicted == labels).squeeze()
        for i in range(len(labels)):
            label = labels[i]
            class_correct[label] += c[i].item()
            class_total[label] += 1


for i in range(10):
    print('Accuracy of %5s : %2d %%' % (
        classes[i], 100 * class_correct[i] / class_total[i]))